version: '3'
services:
  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - '3001:3001'
    links:
      - backend
  backend:
    env_file: 
      - ./server/.env
    container_name: backend
    restart: always
    build: ./server
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
